const assets = {
  icon: {
    camera: '/src/assets/icon/Camera.png',
    gamepad: '/src/assets/icon/Gamepad.png',
    headPhone: '/src/assets/icon/Headphone.png',
    smartWatch: '/src/assets/icon/SmartWatch.png',
    cellPhone: '/src/assets/icon/CellPhone.png',
    computer: '/src/assets/icon/Computer.png',
    googleImg: 'src/assets/icon/googleImg.png',
    rupay: 'src/assets/icon/rupay.png',
    visa: 'src/assets/icon/visa.png',
    mastercard: 'src/assets/icon/mastercard.png',
    nagad: 'src/assets/icon/nagad.png',
    call: 'src/assets/icon/call.png',
    message: 'src/assets/icon/message.png',
    activeSeller:'src/assets/icon/active sellers.png',
    activeCustomber:'src/assets/icon/activeCustomber.png',
    grossSale:'src/assets/icon/grossSale.png',
    productionSale:'src/assets/icon/productionSale.png',
    delivery:'src/assets/icon/delivery.png',
    guarantee:'src/assets/icon/guarantee.png',
    service:'src/assets/icon/service.png',
  },
  banners: {},
  products: {},
  images: {
    jblBox: '/src/assets/image/jbl_boombox.png',
    banner1: '/src/assets/image/bannerImg1.png',
    banner2: '/src/assets/image/bannerImg2.jpg',
    banner3: '/src/assets/image/bannerImg3.jpg',
    applestore: 'src/assets/image/applestore.png',
    facebook: 'src/assets/image/facebook.png',
    googleplay: 'src/assets/image/googleplay.png',
    insta: 'src/assets/image/insta.png',
    linkedin: 'src/assets/image/linkedin.png',
    qrcode: 'src/assets/image/Qrcode.png',
    send: 'src/assets/vector/send.svg',
    twitter: 'src/assets/image/twitter.png',
    shopping: 'src/assets/image/shopping.png',
    aboutImg:'src/assets/image/aboutImg.png',
  },
};

export default assets;
